INSERT INTO alimentos (nome, tipo, origem, natural_processado, temperatura, metodo_preparo, preco, calorias) VALUES 
(‘pão de queijo’, ‘salgado’, ‘Brasil’, ‘natural’, ‘quente’, ‘polvilho e queijo’, 9.00, 408),
('coxinha', 'salgado', 'Brasil', 'natural', 'quente', 'massa de farinha com recheio de frango', 4.00, 200),
('esfirra', 'salgado', '', 'natural', 'quente', 'massa recheada de carne ou queijo assada', 3.00, 150),
('empada', 'salgado', 'português', 'natural', 'quente', 'massa podre com recheio assada', 5.00, 250),
('pão de batata', 'salgado', 'brasileiro', 'natural', 'quente', 'massa de batata com queijo assada', 3.00, 180),
('pastel', 'salgado', 'brasileiro', 'natural', 'quente', 'massa frita recheada de carne ou queijo', 5.00, 300),
('torta de frango', 'salgado', 'brasileiro', 'natural', 'quente', 'massa com recheio de frango assada', 8.00, 250),
('pizza', 'salgado', 'italiano', 'natural', 'quente', 'massa com cobertura de queijo e molho de tomate assada', 40.00, 200),
('cuscuz', 'salgado', 'brasileiro', 'natural', 'quente', 'farinha de milho ou tapioca cozida', 6.00, 180),
('cenoura', 'vegetal', 'universal', 'natural', 'ambiente', 'crua ou cozida', 3.00, 41),
('salame', 'embutido', 'italiano', 'processado', 'frio', 'carne curada e temperada', 10.00, 350),
('pipoca', 'salgado', 'brasileiro', 'natural', 'quente', 'milho estourado', 3.00, 30),
('calabresa', 'embutido', 'brasileiro', 'processado', 'quente', 'linguiça frita ou assada', 7.00, 300),
('arroz', 'cereal', 'asiático', 'natural', 'quente', 'cozido', 6.00, 205),
('alface', 'vegetal', 'universal', 'natural', 'ambiente', 'crua', 4.00, 5),
('milho', 'vegetal', 'universal', 'natural', 'quente', 'cozido ou assado', 4.00, 96),
('ervilha', 'vegetal', 'universal', 'natural', 'quente', 'cozida ou refogada', 3.00, 81),
('brócolis', 'vegetal', 'universal', 'natural', 'quente', 'cozido ou refogado', 7.00, 34),
('mandioca', 'vegetal', 'brasileiro', 'natural', 'quente', 'cozida ou frita', 5.00, 160),
('batata', 'vegetal', 'universal', 'natural', 'quente', 'cozida assada ou frita', 6.00, 77),
('amendoim', 'fruta seca', 'universal', 'natural', 'ambiente', 'cru ou torrado', 4.00, 567),
('ovo', 'proteína', 'universal', 'natural', 'quente', 'cozido ou frito', 1.00, 68),
('frango', 'proteína', 'universal', 'natural', 'quente', 'assado cozido ou grelhado', 20.00, 165),
('salmão', 'proteína', 'universal', 'natural', 'quente', 'grelhado ou assado', 70.00, 206),
('castanha', 'fruta seca', 'universal', 'natural', 'ambiente', 'crua ou torrada', 20.00, 650),
('pão', 'carboidrato', 'universal', 'natural', 'quente', 'assado', 2.00, 80),
('feijão', 'leguminosa', 'brasileiro', 'natural', 'quente', 'cozido', 5.00, 227),
('macarrão', 'carboidrato', 'italiano', 'natural', 'quente', 'cozido', 4.00, 220),
('palmito', 'vegetal', 'brasileiro', 'natural', 'quente', 'cozido ou refogado', 17.00, 37),
('queijo mussarela', 'laticínio', 'italiano', 'natural', 'frio', 'queijo curado', 25.00, 300),
('queijo coalho', 'laticínio', 'brasileiro', 'natural', 'quente', 'assado ou grelhado', 30.00, 360),
('queijo gorgonzola', 'laticínio', 'italiano', 'natural', 'frio', 'queijo curado', 70.00, 350),
('peito de peru', 'embutido', 'universal', 'processado', 'frio', 'fatiado pronto para consumo', 7.00, 135),
('presunto', 'embutido', 'universal', 'processado', 'frio', 'fatiado pronto para consumo', 5.00, 150),
('bacon', 'embutido', 'universal', 'processado', 'quente', 'frito ou assado', 12.00, 541),
('carne', 'proteína', 'universal', 'natural', 'quente', 'grelhada assada ou cozida', 30.00, 250),
('tomate', 'vegetal', 'universal', 'natural', 'ambiente', 'cru ou cozido', 6.00, 18),
('linguiça', 'embutido', 'brasileiro', 'processado', 'quente', 'frita ou assada', 25.00, 300),
('torrada', 'carboidrato', 'universal', 'natural', 'quente', 'pão tostado', 7.00, 40),
('sanduíche', 'salgado', 'universal', 'natural', 'frio', 'pão com recheio', 16.00, 250),
('panqueca', 'salgado', 'universal', 'natural', 'quente', 'massa frita com recheio', 10.00, 100),
('chuchu', 'vegetal', 'universal', 'natural', 'quente', 'cozido', 6.00, 19),
(‘ficasse’, ‘salgado’, ‘francês’, ‘processado’, ‘quente’, ‘assado’, 8.00, 150),  
('bolo salgado', 'salgado', 'universal', 'natural', 'quente', 'assado', 15.00, 250),
('feijoada', 'salgado', 'brasileiro', 'natural', 'quente', 'feijão cozido com carnes', 40.00, 400),
('azeitona', 'fruta', 'mediterrâneo', 'natural', 'frio', 'crua ou em conserva', 9.00, 115),
('strogonoff', 'salgado', 'russiano', 'natural', 'quente', 'carne com molho cremoso', 30.00, 300),
('cogumelo', 'vegetal', 'universal', 'natural', 'quente', 'refogado ou grelhado', 15.00, 22),
('crepioca', 'salgado', 'brasileiro', 'natural', 'quente', 'massa de tapioca com ovo frita', 6.00, 150),
('pimenta', 'condimento', 'universal', 'natural', 'ambiente', 'crua ou em conserva', 5.50, 20),
('sushi', 'salgado', 'japonês', 'natural', 'frio', 'peixe cru com arroz', 50.00, 40),
('pão de alho', 'salgado', 'brasileiro', 'natural', 'quente', 'assado', 6.00, 100),
('taco', 'salgado', 'mexicano', 'natural', 'quente', 'tortilha com recheio', 20.00, 150),
('burrito', 'salgado', 'mexicano', 'natural', 'quente', 'tortilha com recheio', 25.00, 300),
('couve', 'vegetal', 'universal', 'natural', 'quente', 'refogada ou crua', 5.00, 33),
('pepino', 'vegetal', 'universal', 'natural', 'frio', 'cru ou em conserva', 3.00, 16),
('escargot', 'salgado', 'francês', 'natural', 'quente', 'cozido com temperos', 45.00, 90),
('camarão na moranga', 'salgado', 'brasileiro', 'natural', 'quente', 'cozido com abóbora', 50.00, 250),
('nhoque', 'carboidrato', 'italiano', 'natural', 'quente', 'massa de batata cozida', 25.00, 200),
('quibe', 'salgado', 'árabe', 'natural', 'quente', 'frito ou assado', 10.00, 200),
('bolinha de queijo', 'salgado', 'brasileiro', 'natural', 'quente', 'massa frita com recheio de queijo', 5.00, 100),
('risole', 'salgado', 'brasileiro', 'natural', 'quente', 'massa frita com recheio', 5.00, 150),
('cachorro quente', 'salgado', 'americano', 'natural', 'quente', 'pão com salsicha e molhos', 5.00, 300),
('bolinho de bacalhau', 'salgado', 'português', 'natural', 'quente', 'massa frita com bacalhau', 5.00, 100),
('espetinho', 'salgado', 'brasileiro', 'natural', 'quente', 'carne assada no espeto', 3.00, 200),
('coração de galinha', 'proteína', 'brasileiro', 'natural', 'quente', 'assado', 5.00, 170),
('lasanha', 'salgado', 'italiano', 'natural', 'quente', 'massa com camadas e molho assada', 30.00, 250),
('sopa de legumes', 'salgado', 'universal', 'natural', 'quente', 'legumes cozidos em caldo', 13.00, 100),
('risoto', 'carboidrato', 'italiano', 'natural', 'quente', 'arroz cremoso com caldo', 25.00, 300),
('espinafre', 'vegetal', 'universal', 'natural', 'quente', 'refogado ou cozido', 5.00, 23),
('escondidinho de carne', 'salgado', 'brasileiro', 'natural', 'quente', 'carne com purê de batata assado', 24.00, 250),
('farofa', 'acompanhamento', 'brasileiro', 'natural', 'quente', 'farinha de mandioca com temperos', 7.00, 350),
('maionese', 'molho', 'universal', 'processado', 'frio', 'molho à base de ovo e óleo', 3.00, 100),
('mostarda', 'molho', 'universal', 'processado', 'frio', 'molho à base de sementes de mostarda', 3.00, 10),
('salsicha', 'embutido', 'universal', 'processado', 'quente', 'cozida ou frita', 7.00, 150),
('torresmo', 'salgado', 'brasileiro', 'natural', 'quente', 'pele de porco frita', 20.00, 500),
('acarajé', 'salgado', 'brasileiro', 'natural', 'quente', 'massa de feijão frita com recheio', 15.00, 400),
('atum', 'proteína', 'universal', 'natural', 'quente', 'grelhado ou cru', 6.00, 132),
('baião de dois', 'salgado', 'brasileiro', 'natural', 'quente', 'arroz com feijão e carne seca', 15.00, 300),
('moqueca', 'salgado', 'brasileiro', 'natural', 'quente', 'peixe cozido com temperos', 49.99, 350),
('quiabo', 'vegetal', 'brasileiro', 'natural', 'quente', 'cozido ou refogado', 5.00, 33),
('caranguejo', 'proteína', 'brasileiro', 'natural', 'quente', 'cozido', 70.00, 100),
('ostra', 'proteína', 'universal', 'natural', 'frio', 'crua ou cozida', 7.00, 70),
('fígado', 'proteína', 'universal', 'natural', 'quente', 'grelhado ou frito', 20.00, 175),
('rabada', 'proteína', 'brasileiro', 'natural', 'quente', 'cozida', 50.00, 250),
('sarapatel', 'salgado', 'brasileiro', 'natural', 'quente', 'cozido com vísceras', 35.00, 300),
('pamonha', 'salgado', 'brasileiro', 'natural', 'quente', 'massa de milho cozida',5.00, 200),
('omelete', 'salgado', 'universal', 'natural', 'quente', 'ovo batido e frito', 7.00, 90),
('enroladinho de salsicha', 'salgado', 'universal', 'processado', 'quente', 'massa assada com recheio de salsicha', 6.70, 120),
('mortadela', 'embutido', 'italiano', 'processado', 'frio', 'fatiada pronta para consumo', 7.00, 250),
('salpicão', 'salgado', 'brasileiro', 'natural', 'frio', 'salada com frango e vegetais', 20.00, 300),
('vinagrete', 'molho', 'universal', 'natural', 'frio', 'molho de vinagre tomate e cebola', 4.00, 50),
('parmegiana', 'salgado', 'italiano', 'natural', 'quente', 'carne empanada com molho e queijo', 30.00, 400),
('yakisoba', 'salgado', 'japonês', 'natural', 'quente', 'macarrão com vegetais e carne', 25.00, 300),
('kebab', 'salgado', 'árabe', 'natural', 'quente', 'carne assada no espeto', 25.00, 300),
('chipa', 'salgado', 'paraguaio', 'natural', 'quente', 'massa de polvilho e queijo assada', 5.00, 150),
('canapés', 'salgado', 'francês', 'natural', 'frio', 'pequenos aperitivos com base de pão ou biscoito', 8.00, 50),
('caviar', 'salgado', 'universal', 'natural', 'frio', 'ovas de peixe', 200.00, 250),
('misto quente', 'salgado', 'universal', 'natural', 'quente', 'pão com presunto e queijo tostado', 15.00, 350),
('grão de bico', 'leguminosa', 'mediterrâneo', 'natural', 'quente', 'cozido', 9.00, 164);
