INSERT INTO alimentos (nome, tipo, origem, natural_processado, temperatura, metodo_preparo, preco, calorias) VALUES 
(‘Pao de queijo’, ‘salgado’, ‘Brasil’, ‘natural’, ‘quente’, ‘assado’, 9.00, 408),
('Coxinha', 'salgado', 'Brasil', 'natural', 'quente', 'assado', 4.00, 200),
('Esfirra', 'salgado', '', 'natural', 'quente', 'assado', 3.00, 150),
('Empada', 'salgado', 'Portugal', 'natural', 'quente', 'assado', 5.00, 250),
('Pao de batata', 'salgado', 'Brasil', 'natural', 'quente', 'assada', 3.00, 180),
('Pastel', 'salgado', 'Brasil', 'natural', 'quente', 'Frito', 5.00, 300),
('Torta de frango', 'salgado', 'Brasil', 'natural', 'quente', 'assado', 8.00, 250),
('Pizza', 'salgado', 'Italia', 'natural', 'quente', 'assado', 40.00, 200),
('Cuscuz', 'salgado', 'Brasil', 'natural', 'quente', 'cozido', 6.00, 180),
('Cenoura', 'vegetal', 'global', 'natural', 'ambiente', 'crua', 3.00, 41),
('Salame', 'embutido', 'Italia', 'processado', 'frio', 'cru', 10.00, 350),
('Pipoca', 'salgado', 'Brasil', 'natural', 'quente', 'pressao', 3.00, 30),
('Calabresa', 'embutido', 'Brasil', 'processado', 'quente', 'linguiça frita', 7.00, 300),
('Arroz', 'cereal', 'Asia', 'natural', 'quente', 'cozido', 6.00, 205),
('Alface', 'vegetal', 'global', 'natural', 'ambiente', 'crua', 4.00, 5),
('Milho', 'vegetal', 'global', 'natural', 'quente', 'cozido', 4.00, 96),
('Ervilha', 'vegetal', 'global', 'natural', 'quente', 'cozida', 3.00, 81),
('Brócolis', 'vegetal', 'global', 'natural', 'quente', ' refogado', 7.00, 34),
('Mandioca', 'vegetal', 'Brasil', 'natural', 'quente', 'frita', 5.00, 160),
('Batata', 'vegetal', 'global', 'natural', 'quente', ' assada', 6.00, 77),
('Amendoim', 'fruta seca', 'global', 'natural', 'ambiente', 'cru', 4.00, 567),
('Ovo', 'proteína', 'global', 'natural', 'quente', ' frito', 1.00, 68),
('Frango', 'proteína', 'global', 'natural', 'quente', 'grelhado', 20.00, 165),
('Salmao', 'proteína', 'global', 'natural', 'quente', 'grelhado', 70.00, 206),
('Castanha', 'fruta seca', 'global', 'natural', 'ambiente', 'torrada', 20.00, 650),
('Pao', 'carboidrato', 'global', 'natural', 'quente', 'assado', 2.00, 80),
('Feijao', 'leguminosa', 'Brasil', 'natural', 'quente', 'cozido', 5.00, 227),
('Macarrão', 'carboidrato', 'Italia', 'natural', 'quente', 'cozido', 4.00, 220),
('Palmito', 'vegetal', 'Brasil', 'natural', 'quente', 'refogado', 17.00, 37),
('Queijo mussarela', 'laticínio', 'Italia', 'natural', 'frio', 'derivado de leite', 25.00, 300),
('Queijo coalho', 'laticínio', 'Brasil', 'natural', 'quente', 'assado', 30.00, 360),
('Queijo gorgonzola', 'laticínio', 'Italia', 'natural', 'frio', 'derivado de leite', 70.00, 350),
('Peito de peru', 'embutido', 'global', 'processado', 'frio', 'cozido', 7.00, 135),
('Presunto', 'embutido', 'global', 'processado', 'frio', 'cozido', 5.00, 150),
('Bacon', 'embutido', 'global', 'processado', 'quente', 'frito', 12.00, 541),
('Carne', 'proteína', 'global', 'natural', 'quente', 'grelhada’, 30.00, 250),
('Tomate', 'vegetal', 'global', 'natural', 'ambiente', 'cru', 6.00, 18),
('Linguica', 'embutido', 'Brasil', 'processado', 'quente', 'frita', 25.00, 300),
('Torrada', 'carboidrato', 'global', 'processado', 'quente', 'torrada', 7.00, 40),
('Sanduíche', 'salgado', 'global', 'natural', 'frio', 'assado', 16.00, 250),
('Panqueca', 'salgado', 'global', 'natural', 'quente', 'frito', 10.00, 100),
('Chuchu', 'vegetal', 'global', 'natural', 'quente', 'cozido', 6.00, 19),
(‘Fricasse’, ‘salgado’, ‘Franca’, ‘processado’, ‘quente’, ‘assado’, 8.00, 150),  
('Bolo salgado', 'salgado', 'global', 'natural', 'quente', 'assado', 15.00, 250),
('Feijoada', 'salgado', 'Brasil', 'natural', 'quente', 'cozida', 40.00, 400),
('Azeitona', 'fruta', 'Oriente medio', 'natural', 'frio', 'crua', 9.00, 115),
('Strogonoff', 'salgado', 'Russia', 'natural', 'quente', 'cozido', 30.00, 300),
('Cogumelo', 'vegetal', 'global', 'natural', 'quente', 'refogado', 15.00, 22),
('Crepioca', 'salgado', 'Brasil', 'natural', 'quente', ‘assada', 6.00, 150),
('Pimenta', 'condimento', 'global', 'natural', 'ambiente', 'crua', 5.50, 20),
('Sushi', 'salgado', 'Japao', 'natural', 'frio', ' cru', 50.00, 40),
('Pao de alho', 'salgado', 'Brasil', 'natural', 'quente', 'assado', 6.00, 100),
('Taco', 'salgado', 'Mexico', 'natural', 'quente', 'tostado', 20.00, 150),
('Burrito', 'salgado', 'Mexico', 'natural', 'quente', 'tostado', 25.00, 300),
('Couve', 'vegetal', 'global', 'natural', 'quente', 'crua', 5.00, 33),
('Pepino', 'vegetal', 'global', 'natural', 'frio', 'cru', 3.00, 16),
('Escargot', 'salgado', 'Franca', 'natural', 'quente', 'cozido', 45.00, 90),
('Camarão na moranga', 'salgado', 'Brasil', 'natural', 'quente', 'cozido', 50.00, 250),
('Nhoque', 'carboidrato', 'Italia', 'natural', 'quente', 'cozido', 25.00, 200),
('Quibe', 'salgado', 'Arabe', 'natural', 'quente', 'frito', 10.00, 200),
('Bolinha de queijo', 'salgado', 'Brasil', 'natural', 'quente', 'frito', 5.00, 100),
('Risole', 'salgado', 'Brasil', 'natural', 'quente', 'frito', 5.00, 150),
('Cachorro quente', 'salgado', 'EUA', 'natural', 'quente', 'assado', 5.00, 300),
('Bolinho de bacalhau', 'salgado', 'Portugal', 'natural', 'quente', 'frito', 5.00, 100),
('Espetinho', 'salgado', 'Brasil', 'natural', 'quente', 'assado', 3.00, 200),
('Coracao de galinha', 'proteína', 'Brasil', 'natural', 'quente', 'assado', 5.00, 170),
('Lasanha', 'salgado', 'Italia', 'natural', 'quente', 'assada', 30.00, 250),
('Sopa de legumes', 'salgado', 'global', 'natural', 'quente', 'cozido', 13.00, 100),
('Risoto', 'carboidrato', 'Italia', 'natural', 'quente', 'cozido', 25.00, 300),
('Espinafre', 'vegetal', 'global', 'natural', 'quente', 'cozido', 5.00, 23),
('Escondidinho de carne', 'salgado', 'Brasil', 'natural', 'quente', 'assado', 24.00, 250),
('Farofa', 'acompanhamento', 'Brasil', 'natural', 'quente', 'cozido', 7.00, 350),
('Maionese', 'molho', 'global', 'processado', 'frio', 'cozido', 3.00, 100),
('Mostarda', 'molho', 'global', 'processado', 'frio', 'cru', 3.00, 10),
('Salsicha', 'embutido', 'global', 'processado', 'quente', 'cozida', 7.00, 150),
('Torresmo', 'salgado', 'Brasil', 'natural', 'quente', ' frito', 20.00, 500),
('Acaraje', 'salgado', 'Brasil', 'natural', 'quente', 'frita', 15.00, 400),
('Atum', 'proteína', 'global', 'natural', 'quente', 'grelhado', 6.00, 132),
('Baiao de dois', 'salgado', 'Brasil', 'natural', 'quente', 'cozido', 15.00, 300),
('Moqueca', 'salgado', 'Brasil', 'natural', 'quente', 'cozido', 49.99, 350),
('Quiabo', 'vegetal', 'Brasil', 'natural', 'quente', 'refogado', 5.00, 33),
('Caranguejo', 'proteína', 'Brasil', 'natural', 'quente', 'cozido', 70.00, 100),
('Ostra', 'proteína', 'global', 'natural', 'frio', 'crua', 7.00, 70),
('Figado', 'proteína', 'global', 'natural', 'quente', 'frito', 20.00, 175),
('Rabada', 'proteína', 'Brasil', 'natural', 'quente', 'cozida', 50.00, 250),
('Sarapatel', 'salgado', 'Brasil', 'natural', 'quente', 'cozido', 35.00, 300),
('Pamonha', 'salgado', 'Brasil', 'natural', 'quente', 'cozida',5.00, 200),
('Omelete', 'salgado', 'global', 'natural', 'quente', 'frito', 7.00, 90),
('Enroladinho de salsicha', 'salgado', 'global', 'processado', 'quente', 'assado', 6.70, 120),
('mortadela', 'embutido', 'Italia', 'processado', 'frio', 'fatiada pronta para consumo', 7.00, 250),
('Salpicao', 'salgado', 'Brasil', 'natural', 'frio', 'cozida', 20.00, 300),
('Vinagrete', 'molho', 'global', 'natural', 'frio', 'cozido', 4.00, 50),
('Parmegiana', 'salgado', 'Italia', 'natural', 'quente', 'frita', 30.00, 400),
('Yakisoba', 'salgado', 'Japao', 'natural', 'quente', 'cozido', 25.00, 300),
('Kebab', 'salgado', 'Arabe', 'natural', 'quente', 'assado', 25.00, 300),
('Chipa', 'salgado', 'Paraguai', 'natural', 'quente', 'assada', 5.00, 150),
('Canapés', 'salgado', 'Franca', 'natural', 'frio', 'frito', 8.00, 50),
('Caviar', 'salgado', 'global', 'natural', 'frio', 'cozido', 200.00, 250),
('Misto quente', 'salgado', 'global', 'natural', 'quente', 'tostado', 15.00, 350),
('Grão de bico', 'leguminosa', 'Oriente medio', 'natural', 'quente', 'cozido', 9.00, 164);
