UPDATE alimentos SET preco = 3.50 WHERE nome = 'Morango';
UPDATE alimentos SET regiao = 'tropical' WHERE titulo = 'Jabuticaba';
UPDATE alimentos SET metodo_preparo = 'processado' WHERE regiao = 'global';
UPDATE alimentos SET calorias = 84 WHERE nome = 'Banana';
UPDATE alimentos SET tipo = 'salgado' WHERE nome = 'Pavlova';
UPDATE alimentos SET preco = 6.50 WHERE regiao = 'Brasil';
UPDATE alimentos SET metodo_preparo = 'grelhado' WHERE tipo = 'salgado';
UPDATE alimentos SET temperatura= 'frio' WHERE preco = 3.50 ;
UPDATE alimentos SET temperatura = 'frio' WHERE natural_processado = 'natural';
UPDATE alimentos SET calorias = 80 WHERE tipo = 'fruta';
UPDATE alimentos SET nome = 'Brigadeirão' WHERE preco = 7.50;
UPDATE alimentos SET nome = 'Coco' WHERE nome = 'Cocada';
UPDATE alimentos SET metodo_preparo = 'cru' WHERE regiao = 'tropical';
UPDATE alimentos SET preco = 10.00 WHERE temperatura = 'ambiente';
UPDATE alimentos SET metodo_preparo = 'assado' WHERE natural_processado = 'natural';
UPDATE alimentos SET calorias = calorias - 5 WHERE temperatura = 'ambiente';
UPDATE alimentos SET preco = preco * 1.05 WHERE metodo_preparo = 'cozido';
UPDATE alimentos SET temperatura = 'ambiente' WHERE preco = 5.00;
UPDATE alimentos SET metodo_preparo = 'frito' WHERE calorias < 100;
UPDATE alimentos SET natural_processado = 'natural' WHERE calorias > 200;
UPDATE alimentos SET preco = preco * 1.05 WHERE nome = 'Maçã';
UPDATE alimentos SET metodo_preparo = 'assado' WHERE nome = 'Abacaxi';
UPDATE alimentos SET temperatura = 'ambiente' WHERE nome = 'Bolo de Cenoura com Chocolate';
UPDATE alimentos SET regiao = 'global' WHERE regiao = 'tropical';
UPDATE alimentos SET preco = preco * 0.85 WHERE regiao = 'Universal';
UPDATE alimentos SET calorias = calorias + 15 WHERE natural_processado = 'processado';
UPDATE alimentos SET tipo = 'salgado' WHERE natural_processado = 'processado';
UPDATE alimentos SET preco = preco * 1.07 WHERE temperatura = 'frio';
UPDATE alimentos SET regiao = 'tropical' WHERE temperatura = 'ambiente';
UPDATE alimentos SET calorias = calorias + 5 WHERE metodo_preparo = 'assado';
UPDATE alimentos SET preco = preco * 0.95 WHERE metodo_preparo = 'grelhado';
UPDATE alimentos SET natural_processado = 'natural' WHERE preco < 5.00;
UPDATE alimentos SET calorias = calorias + 10 WHERE preco > 40.00;
UPDATE alimentos SET preco = preco + 1.10 WHERE calorias < 150;
UPDATE alimentos SET temperatura = 'refrigerado' WHERE calorias < 50;
UPDATE alimentos SET metodo_preparo = 'frito' WHERE nome = 'Petit Gateau';
UPDATE alimentos SET preco = preco * 1.20 WHERE nome = 'Morango';
UPDATE alimentos SET origem = 'Brasil' WHERE tipo = 'vegetal';
UPDATE alimentos SET temperatura = 'ambiente' WHERE nome = 'cuscuz';
UPDATE alimentos SET preco = preco * 0.92 WHERE origem = 'Arabia';
UPDATE alimentos SET calorias = calorias - 15 WHERE regiao = 'Portugal';