SELECT * FROM alimentos;
SELECT nome FROM alimentos;
SELECT tipo FROM alimentos;
SELECT origem FROM alimentos;
SELECT natural_processado FROM alimentos;
SELECT temperatura FROM alimentos;
SELECT metodo_preparo FROM alimentos;
SELECT preco FROM alimentos;
SELECT calorias FROM alimentos;
SELECT * FROM alimentos WHERE tipo = 'fruta';
SELECT * FROM alimentos WHERE tipo = 'doce';
SELECT * FROM alimentos WHERE origem = 'Brasil';
SELECT * FROM alimentos WHERE natural_processado = 'natural';
SELECT * FROM alimentos WHERE preco > 3.0;
SELECT * FROM alimentos WHERE calorias > 60;
SELECT * FROM alimentos ORDER BY preco ASC;
SELECT * FROM alimentos ORDER BY preco DESC;
SELECT * FROM alimentos ORDER BY calorias ASC;
SELECT * FROM alimentos ORDER BY calorias DESC;
SELECT * FROM alimentos ORDER BY preco DESC LIMIT 1;
SELECT * FROM alimentos ORDER BY preco ASC LIMIT 1;
SELECT * FROM alimentos ORDER BY calorias DESC LIMIT 1;
SELECT * FROM alimentos ORDER BY calorias ASC LIMIT 1;
SELECT * FROM alimentos WHERE calorias BETWEEN 50 AND 80;
SELECT * FROM alimentos WHERE preco BETWEEN 2000 AND 2020;
SELECT * FROM alimentos WHERE nome LIKE 'S%';
SELECT * FROM alimentos WHERE nome LIKE 'D%';
SELECT * FROM alimentos WHERE nome LIKE 'A%' AND temperatura = 'ambiente';
SELECT * FROM alimentos WHERE preco > 5.0 AND tipo = 'doce';
SELECT * FROM alimentos WHERE metodo_preparo = 'cozido' AND origem = 'global';
SELECT * FROM alimentos WHERE tipo = 'salgado';
SELECT * FROM alimentos WHERE tipo = 'vegetal';
SELECT * FROM alimentos WHERE origem = 'Brasil'
SELECT * FROM alimentos WHERE temperatura = 'quente';
SELECT * FROM alimentos WHERE temperatura = 'frio';
SELECT * FROM alimentos WHERE tipo = 'proteína';
SELECT * FROM alimentos WHERE tipo = 'carboidrato';
SELECT * FROM alimentos WHERE tipo = 'molho';
SELECT * FROM alimentos WHERE tipo = 'laticínio';
SELECT * FROM alimentos WHERE tipo = 'embutido';
SELECT * FROM alimentos WHERE tipo = 'fruta';
SELECT * FROM alimentos WHERE tipo = 'leguminosa' AND preco < 5.0;
SELECT * FROM alimentos WHERE origem = 'árabe';
SELECT * FROM alimentos WHERE metodo_preparo LIKE 'M%';
SELECT * FROM alimentos WHERE metodo_preparo = 'pressao';
SELECT * FROM alimentos WHERE metodo_preparo = 'crua';
SELECT * FROM alimentos WHERE origem = 'França' AND nome LIKE 'C%';
SELECT * FROM alimentos WHERE origem = 'Amazônia';
SELECT * FROM alimentos WHERE preco = 4.00;
SELECT * FROM alimentos WHERE nome LIKE '%O';
SELECT * FROM alimentos WHERE nome LIKE '%L';
SELECT * FROM alimentos WHERE id BETWEEN 162 AND 185;
SELECT * FROM alimentos WHERE nome LIKE 'B%';
SELECT * FROM alimentos WHERE nome LIKE 'C%';
SELECT * FROM alimentos WHERE tipo LIKE 'D%';
SELECT * FROM alimentos WHERE id BETWEEN 30 AND 76;
SELECT * FROM alimentos WHERE tipo = 'salgado' AND metodo_preparo = 'in natura';
SELECT * FROM alimentos WHERE temperatura = 'ambiente' AND nome LIKE 'K%';
SELECT * FROM alimentos WHERE origem = 'Austrália';
SELECT * FROM alimentos WHERE calorias < 50;